from abs_error import abs_error
from rel_error import rel_error



from calculate_single_float_precision import calculate_single_float_precision
from calculate_double_float_precision import calculate_double_float_precision

from root_solve_bisection import root_solve_bisection
from root_solve_fixed_point import root_solve_fixed_point
from root_solve_newton import  root_solve_newton
from root_solve_secant import root_solve_secant
from root_solve_newton_hybrid import root_solve_newton_hybrid
from root_solve_secant_hybrid import root_solve_secant_hybrid

from vector_add import vector_add
from vector_scal_mult import vector_scal_mult
from vector_sub import vector_sub
from vector_1norm import vector_1norm
from vector_2norm import vector_2norm
from vector_infnorm import vector_infnorm
from vector_SAXPY import vector_SAXPY
from vector_cross import vector_cross
from vector_dot import vector_dot

from matrix_vec_mult import matrix_vec_mult

from abs_error_1norm import abs_error_1norm
from abs_error_2norm import abs_error_2norm
from abs_error_infnorm import abs_error_infnorm